name: Code Coverage and CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Cache SonarCloud
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: sonar-${{ runner.os }}

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Add tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore
      run: dotnet restore ./PatternFinder/PatternFinder/PatternFinder.csproj

    - name: Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"saikatkrroy_24e2a906-733f-4edb-abd1-c9fe871d60d7" \
          /o:"saikatkrroy" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="$SONAR_TOKEN"

    - name: Build
      run: dotnet build ./PatternFinder/PatternFinder/PatternFinder.csproj --no-restore

    - name: Test with coverage
      run: |
        dotnet test ./PatternFinder/PatternFinder.Test/PatternFinder.Test.csproj \
        --configuration Release \
        --collect:"XPlat Code Coverage" \
        --results-directory ./TestResults

    - name: List test results
      run: find ./TestResults -type f

    - name: Generate OpenCover report
      run: |
        reportgenerator \
          -reports:"./TestResults/**/coverage.cobertura.xml" \
          -targetdir:"./coverage" \
          -reporttypes:opencover

    - name: Verify OpenCover file
      run: ls -R ./coverage

    - name: End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
