name: Code Coverage and CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Add tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"saikatkrroy_24e2a906-733f-4edb-abd1-c9fe871d60d7" \
          /o:"saikatkrroy" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.cs.opencover.reportsPaths=coverage/coverage.opencover.xml

    - name: Restore dependencies
      run: dotnet restore ./PatternFinder/PatternFinder/PatternFinder.csproj

    - name: Build Project
      run: dotnet build ./PatternFinder/PatternFinder/PatternFinder.csproj --no-restore

    - name: Install coverage tool
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Run Unit Tests with coverage
      run: |
        dotnet test ./PatternFinder/PatternFinder.Test/PatternFinder.Test.csproj \
        --collect:"XPlat Code Coverage" \
        --results-directory ./TestResults

    - name: Convert coverage report
      run: |
        reportgenerator \
          -reports:"**/TestResults/**/coverage.cobertura.xml" \
          -targetdir:"coverage" \
          -reporttypes:opencover

    - name: Verify coverage file exists
      run: find . -name "coverage.opencover.xml"

    - name: End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
